name = "fastapi"
compatibility_date = "2024-05-20"

[vars]
UPSTASH_REDIS_REST_TOKEN = 'AZV1AAIncDE0YzM0ZWViNGE4ZGE0OGEyYjRhNjU0ODE2Yzg0YjI3N3AxMzgyNjE'
UPSTASH_REDIS_REST_URL = 'https://tough-seagull-38261.upstash.io'