name = "fastapi"
compatibility_date = "2024-05-20"

[vars]
UPSTASH_REDIS_REST_TOKEN = 'AZV1AAIncDEyMzI1MGU1YmZkOTI0NWQxODVkZWU3ZTZiMmRkZWY3MHAxMzgyNjE'
UPSTASH_REDIS_REST_URL = 'https://tough-seagull-38261.upstash.io'